print ('XXXXXxX xxxXXXXXX')
print ('  xXX      xXX')
print ('    X      XX')
print ('     X   xX')
print ('      xx xX')
print ('        X')
print ('      xX xx')
print ('     Xx   Xx')
print ('    XX     XX')
print ('  xXX       XX')
print ('xXXXXXXXXx XXXXxXx')